# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [10]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [2]:
# your code here
np.version


<module 'numpy.version' from '/Users/naitsaidifariza/opt/anaconda3/lib/python3.9/site-packages/numpy/version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
import random
a=np.random.random((2,3,5))
a

array([[[0.28968613, 0.5477472 , 0.91498881, 0.95390338, 0.18433405],
        [0.92844022, 0.67199462, 0.41743569, 0.54347315, 0.18113222],
        [0.04825798, 0.90425943, 0.40474886, 0.43409648, 0.15605533]],

       [[0.76300877, 0.20316604, 0.89571904, 0.79425461, 0.52094842],
        [0.73928937, 0.09511897, 0.73593995, 0.53776647, 0.05871894],
        [0.64465398, 0.67027863, 0.2229631 , 0.32920057, 0.63508695]]])

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [56]:
# your code here
print(a)
a= np.array([(2,3,5)])
a


[[2 3 5]]


array([[2, 3, 5]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here

# your code here
b=np.full((5,2,3),1,dtype=float)
b.shape

(5, 2, 3)

#### 6. Print *b*.


In [13]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here
a.size==b.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?



It is impossible because even though the sizes are the same, the dimensions are different.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
# your code here
c=b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [18]:
# your code/answer here
d=a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [19]:
# your code/answer here
a

array([[[0.28968613, 0.5477472 , 0.91498881, 0.95390338, 0.18433405],
        [0.92844022, 0.67199462, 0.41743569, 0.54347315, 0.18113222],
        [0.04825798, 0.90425943, 0.40474886, 0.43409648, 0.15605533]],

       [[0.76300877, 0.20316604, 0.89571904, 0.79425461, 0.52094842],
        [0.73928937, 0.09511897, 0.73593995, 0.53776647, 0.05871894],
        [0.64465398, 0.67027863, 0.2229631 , 0.32920057, 0.63508695]]])

In [21]:
d

array([[[1.28968613, 1.5477472 , 1.91498881, 1.95390338, 1.18433405],
        [1.92844022, 1.67199462, 1.41743569, 1.54347315, 1.18113222],
        [1.04825798, 1.90425943, 1.40474886, 1.43409648, 1.15605533]],

       [[1.76300877, 1.20316604, 1.89571904, 1.79425461, 1.52094842],
        [1.73928937, 1.09511897, 1.73593995, 1.53776647, 1.05871894],
        [1.64465398, 1.67027863, 1.2229631 , 1.32920057, 1.63508695]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
e=a*c
e

array([[[0.28968613, 0.5477472 , 0.91498881, 0.95390338, 0.18433405],
        [0.92844022, 0.67199462, 0.41743569, 0.54347315, 0.18113222],
        [0.04825798, 0.90425943, 0.40474886, 0.43409648, 0.15605533]],

       [[0.76300877, 0.20316604, 0.89571904, 0.79425461, 0.52094842],
        [0.73928937, 0.09511897, 0.73593995, 0.53776647, 0.05871894],
        [0.64465398, 0.67027863, 0.2229631 , 0.32920057, 0.63508695]]])

In [ ]:
# your code here

#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
# your code/answer here
e==a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [27]:
# your code here
f=np.empty((2,3,5))
f

array([[[0.28968613, 0.5477472 , 0.91498881, 0.95390338, 0.18433405],
        [0.92844022, 0.67199462, 0.41743569, 0.54347315, 0.18113222],
        [0.04825798, 0.90425943, 0.40474886, 0.43409648, 0.15605533]],

       [[0.76300877, 0.20316604, 0.89571904, 0.79425461, 0.52094842],
        [0.73928937, 0.09511897, 0.73593995, 0.53776647, 0.05871894],
        [0.64465398, 0.67027863, 0.2229631 , 0.32920057, 0.63508695]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k]<d_mean and d[i,j,k]>d_min:
                f[i,j,k]=25
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_max:
                f[i,j,k]=100
            

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [29]:
# your code here
d

array([[[1.28968613, 1.5477472 , 1.91498881, 1.95390338, 1.18433405],
        [1.92844022, 1.67199462, 1.41743569, 1.54347315, 1.18113222],
        [1.04825798, 1.90425943, 1.40474886, 1.43409648, 1.15605533]],

       [[1.76300877, 1.20316604, 1.89571904, 1.79425461, 1.52094842],
        [1.73928937, 1.09511897, 1.73593995, 1.53776647, 1.05871894],
        [1.64465398, 1.67027863, 1.2229631 , 1.32920057, 1.63508695]]])

In [30]:
f

array([[[ 25.,  75.,  75., 100.,  25.],
        [ 75.,  75.,  25.,  75.,  25.],
        [  0.,  75.,  25.,  25.,  25.]],

       [[ 75.,  25.,  75.,  75.,  75.],
        [ 75.,  25.,  75.,  75.,  25.],
        [ 75.,  75.,  25.,  25.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [32]:
f=f.astype(np.str_)

In [33]:
# your code here
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k]<d_mean and d[i,j,k]>d_min:
                f[i,j,k]='B'
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]='D'
            elif d[i,j,k]==d_mean:
                f[i,j,k]='C'
            elif d[i,j,k]==d_min:
                f[i,j,k]='A'
            elif d[i,j,k]==d_max:
                f[i,j,k]='E'
f

array([[['B', 'D', 'D', 'E', 'B'],
        ['D', 'D', 'B', 'D', 'B'],
        ['A', 'D', 'B', 'B', 'B']],

       [['D', 'B', 'D', 'D', 'D'],
        ['D', 'B', 'D', 'D', 'B'],
        ['D', 'D', 'B', 'B', 'D']]], dtype='<U32')