## Project 7 (Personal Loan)

In [295]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [296]:
df=pd.read_csv(r'/Users/alix/Documents/Bank_Personal_Loan_Modelling.csv')

In [297]:
df.columns

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [298]:
from autoviz.AutoViz_Class import AutoViz_Class

In [299]:
df.to_csv('Bank_Personal_Loan_Modelling.csv')

In [300]:
av= AutoViz_Class()
sep=","
viz=av.AutoViz('Bank_Personal_Loan_Modelling.csv', sep=',', chart_format="html")

Shape of your Data Set loaded: (5000, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...


    15 Predictors classified...
        2 variables removed since they were ID or low-information variables
        List of variables removed: ['Unnamed: 0', 'ID']
No scatter plots with depVar when no depVar is given.
Saving distplots_nums in HTML format
Saving violinplots in HTML format                                               
Saving cat_var_plots in HTML format
Time to run AutoViz (in seconds) = 1                                            


In [284]:
df=df.rename(columns={"Securities Account": "Securities_Account", "CD Account": "CD_Account", 'Personal Loan': 'Personal_Loan'})

In [285]:
df.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal_Loan         0
Securities_Account    0
CD_Account            0
Online                0
CreditCard            0
dtype: int64

In [286]:
df.loc[(df["Experience"]<0),"Experience"]=0

In [287]:
df.to_csv(r'/Users/alix/project7_fianl.csv')

##  EDA using Autoviz

In [288]:
pip install AutoViz

Note: you may need to restart the kernel to use updated packages.


In [289]:
from autoviz.AutoViz_Class import AutoViz_Class

In [290]:
df.to_csv('Bank_Personal_Loan_Modelling.csv')

In [291]:
av= AutoViz_Class()
sep=","
viz=av.AutoViz('Bank_Personal_Loan_Modelling.csv', sep=',', chart_format="html")

Shape of your Data Set loaded: (5000, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...


    15 Predictors classified...
        2 variables removed since they were ID or low-information variables
        List of variables removed: ['Unnamed: 0', 'ID']
No scatter plots with depVar when no depVar is given.
Saving distplots_nums in HTML format
Saving violinplots in HTML format                                               
Saving cat_var_plots in HTML format
Time to run AutoViz (in seconds) = 1                                            


## Fix our column "target" and 'features' that we assume relevent.

In [159]:
y=df[['Personal_Loan']]
x=df[['Age','Experience','Income', 'Family', 'CCAvg', 'Education', 'Mortgage', 'Securities_Account', 'CD_Account']]

## train_test_split

In [160]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, train_size=0.8)

In [18]:
f'{x_train.shape},{x_test.shape}' 

'(4000, 9),(1000, 9)'

## Standardization

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##  PCA

In [108]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
x_PCA = pca.fit(x_train).transform(x_train)
#x_test = pca.transform(x_test)

### Variance of each componment

In [109]:
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.82185872, 0.15718756])

In [110]:
import plotly.express as px
import matplotlib.pyplot as plt
#
plt.figure(figsize=(20,20))
fig = px.scatter_matrix(
    df,
    dimensions=x,
    color="Personal_Loan"
)
fig.update_traces(diagonal_visible=False)
fig.show()

In [111]:
y=df[['Personal_Loan']]
x=df[['Age','Experience','Income', 'Family', 'CCAvg', 'Education', 'Mortgage', 'Securities_Account', 'CD_Account', 'Personal_Loan']]


pca = PCA(n_components=3)
components = pca.fit_transform(x)

total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter_3d(
    components, x=0, y=1, z=2, color=df['Personal_Loan'],
    title=f'Total Explained Variance: {total_var:.2f}%',
    labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'}
)
fig.show()

## SVC (Support Vector Classifier)

class sklearn.svm.SVC(C=1.0, kernel='rbf', degree=3, gamma=0.0, coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, scale_C=True, class_weight=None)

In [112]:
from sklearn.svm import SVC

In [113]:
model=SVC(kernel='linear')

In [114]:
model.fit(x_train, y_train)

SVC(kernel='linear')

In [115]:
score=model.score(x_train, y_train)
score

0.94775

In [119]:
model.predict(x_test)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## Cross validation

In [120]:
from sklearn.model_selection import cross_val_score

In [121]:
model= SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(model, x_train, y_train, cv=5)
scores
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.95 accuracy with a standard deviation of 0.01


In [122]:
## The accuracy is hight with a sdev close to 0.

## Linear discriminant analysis 

sklearn.discriminant_analysis.LinearDiscriminantAnalysis(solver='svd', shrinkage=None, priors=None, n_components=None, store_covariance=False, tol=0.0001, covariance_estimator=None)

In [123]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [124]:
model=LinearDiscriminantAnalysis()

In [125]:
model.fit(x_train, y_train)

LinearDiscriminantAnalysis()

In [126]:
f' The acurracy on train set is {model.score(x_train, y_train)*100} % and for test set is  {model.score(x_test, y_test)*100} %' 

' The acurracy on train set is 94.19999999999999 % and for test set is  94.39999999999999 %'

In [127]:
explained_variance = model.explained_variance_ratio_
explained_variance

array([1.])

## Linear discriminant analysis 

sklearn.discriminant_analysis.LinearDiscriminantAnalysis(solver='svd', shrinkage=None, priors=None, n_components=None, store_covariance=False, tol=0.0001, covariance_estimator=None)

In [128]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [129]:
model=LinearDiscriminantAnalysis()

In [130]:
model.fit(x_train, y_train)

LinearDiscriminantAnalysis()

In [131]:
f' The acurracy on train set is {model.score(x_train, y_train)*100} % and for test set is  {model.score(x_test, y_test)*100} %' 

' The acurracy on train set is 94.19999999999999 % and for test set is  94.39999999999999 %'

## KNeighborsClassifier

sklearn.neighbors.KNeighborsClassifier(n_neighbors=5, *, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)

In [132]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()

In [133]:
model.fit(x_train, y_train)

KNeighborsClassifier()

In [134]:
score= model.score(x_train, y_train)
score

0.938

## Ridge Classifier




In [161]:
from sklearn import linear_model
from sklearn.linear_model import RidgeClassifier
reg = linear_model.RidgeClassifier(alpha=0.1)
reg.fit(x_train, y_train)


RidgeClassifier(alpha=0.1)

In [162]:
x_train

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
4567   46          20      19       3    0.5          2        97   
467    45          20      39       1    2.4          1         0   
3375   43          18      88       4    1.1          2         0   
1713   44          20      15       1    1.0          1         0   
2601   50          24      32       1    1.4          3       167   
...   ...         ...     ...     ...    ...        ...       ...   
3358   59          35      40       4    0.4          1         0   
3710   49          22      23       2    1.0          2         0   
1237   38          13     169       1    6.8          3         0   
1579   29           5     122       4    3.0          1         0   
3777   62          37      98       1    0.9          1       151   

      Securities_Account  CD_Account  
4567                   1           0  
467                    0           0  
3375                   0           0  
1713                   0           0  
2601                   0           0  
...                  ...         ...  
3358                   0           0  
3710                   0           0  
1237                   0           1  
1579                   0           0  
3777                   0           0  

[4000 rows x 9 columns]

In [163]:
y_pred = reg.predict(x_test)
result= reg.score (x_test, y_test)
print('The accuracy of the RidgeClassifier Classifier is:', result * 100, '%')

The accuracy of the RidgeClassifier Classifier is: 93.5 %


In [164]:
x_test["y_initial"]=y_test
x_test["y_pred"]=y_pred

In [165]:
x_test["y_initial"].value_counts()
x_test["y_pred"].value_counts()

0    967
1     33
Name: y_pred, dtype: int64

In [166]:
pd.crosstab(x_test["y_initial"],x_test["y_pred"])

y_pred       0   1
y_initial         
0          906   4
1           61  29

## Confusion_matrix

In [167]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
metrics.confusion_matrix(x_test["y_initial"],x_test["y_pred"])

array([[906,   4],
       [ 61,  29]])

In [173]:
import seaborn as sns
cm_model = confusion_matrix(y_test, y_pred)

plt.figure(figsize = (6, 4))
sns.heatmap(cm_model, annot = True, cmap = 'OrRd', annot_kws = {'size':15}, square = True)
x_test["y_initial"]=y_test
x_test["y_pred"]=y_pred


In [174]:
pd.crosstab(x_test["y_initial"],x_test["y_pred"])

y_pred       0   1
y_initial         
0          906   4
1           61  29

In [170]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier

In [172]:

clf = GradientBoostingClassifier ()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)


ValueError: X has 11 features, but GradientBoostingClassifier is expecting 9 features as input.

## Metrics for checking accuracy

### Confusion Matrix

In [175]:
from sklearn import metrics
y_pred = model.predict(x_test)
conf_matrix=metrics.confusion_matrix(y_test,y_pred)

ValueError: X has 11 features, but KNeighborsClassifier is expecting 9 features as input.

In [176]:
from sklearn.metrics import roc_auc_score
print(metrics.roc_auc_score(y_test,y_pred))

0.6589133089133089


In [178]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_pred)
roc_auc = metrics.auc(fpr, tpr)
display = metrics.RocCurveDisplay(fpr=fpr, tpr=tpr)
display.plot()
plt.show()

In [179]:
from sklearn.metrics import f1_score

## f1_score
### F1 = 2 * (precision * recall) / (precision + recall)

In [181]:
average=[None,'micro', 'macro', 'weighted']
for i in average:
    print(f1_score(y_test, y_pred, average=i))

[0.96537027 0.47154472]
0.935
0.7184574935786652
0.9209259716465039


In [182]:
# f1 is close to unity, that means a significant score.

In [196]:
import seaborn as sns
sns.heatmap(conf_matrix, annot=True, cmap='binary')

NameError: name 'conf_matrix' is not defined

In [197]:
import numpy as np
import matplotlib.pyplot as plt
plt.figure(figsize=(14,14))
group_names =['True negative','False positive','False negative','true positive']
group_counts = ["{0:0.0f}".format(value) for value in
                conf_matrix.flatten()]
group_percentages = ['{0:.2%}'.format(value) for value in
                     conf_matrix.flatten()/np.sum(conf_matrix)]
labels = [f"{v1}\n{v2}\n{v3}" for v1, v2, v3 in
          zip(group_names,group_counts,group_percentages)]
labels = np.asarray(labels).reshape(2,2)
sns.heatmap(conf_matrix, annot=labels, fmt='', cmap='Blues')

NameError: name 'conf_matrix' is not defined

In [351]:
import emoji

## Predictions on some samples

In [352]:
x_sample=pd.DataFrame([30,1,150,4,0,3,0,0,0]).T
#['Age','Experience','Income', 'Family', 'CCAvg', 'Education', 'Mortgage', 'Securities Account', 'CD Account']]
x_sample

0  1    2  3  4  5  6  7  8
0  30  1  150  4  0  3  0  0  0

In [353]:
l=[]
Age=input('please insert your age')
l.append(int(Age))

please insert your age40


In [354]:
Experience=input('please insert your experience')
l.append(int(Experience))

please insert your experience12


In [355]:
Income = input('please insert your income')

please insert your income26


In [356]:
l.append(int(Income))

In [357]:
Family  = input('please insert the number of your family members')

please insert the number of your family members1


In [358]:
l.append(int(Family))

In [360]:
CCAvg = input('please insert your CCAvg')

please insert your CCAvg1


In [361]:
l.append(int(CCAvg))

In [362]:
Education = input('please insert your level of education')

please insert your level of education3


In [363]:
l.append(int(Education))

In [364]:
Mortgage = input('please insert the amount of your current mortgage') 

please insert the amount of your current mortgage0


In [365]:
l.append(int(Mortgage))

In [366]:
Securities_Account= input(' Do you have a security account?')

 Do you have a security account?1


In [367]:
l.append(int(Securities_Account))

In [368]:
CD_Account = input('Do you have a certificate of deposit?' )

Do you have a certificate of deposit?1


In [369]:
l.append(int(CD_Account))


In [370]:
ll=pd.DataFrame(l).T
ll

0   1   2  3  4  5  6  7  8
0  40  12  26  1  1  3  0  1  1

In [371]:

model.predict(ll)
if model.predict(ll)==0:
    print('Sorry Loan,  not granted ')
    print(emoji.emojize(":zipper-mouth_face:"))
else:
    print('Congrats: Loan granted')
    print(emoji.emojize(":winking_face_with_tongue:"))
    

Sorry Loan,  not granted 
🤐


In [323]:
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [208]:
y=df[['Personal_Loan']]
x=df[['Age','Experience','Income', 'Family', 'CCAvg', 'Education', 'Mortgage', 'Securities_Account', 'CD_Account']]

NameError: name 'x_example' is not defined

In [238]:
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal_Loan  Securities_Account  CD_Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [254]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [255]:
LSVC= make_pipeline(StandardScaler(), LinearSVC(random_state=0, tol=1e-5))
LSVC.fit(x_train, y_train)
y_pred3=LSVC.predict(x_test)

ValueError: X has 11 features, but StandardScaler is expecting 9 features as input.

In [ ]:
print("The accuracy of the LinearSVC is",accuracy_score(y_test, y_pred3)*100,"%")